/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","promise"],function(b,f){b.Hd=function(){this.Init()};b.b.ga(b.Hd,b.Mg,"oj.FilmStripPagingModel");b.Hd.prototype.Init=function(){b.Hd.q.Init.call(this);this.Mc=-1;this.ke=0;this.La=-1};b.b.g("FilmStripPagingModel.prototype.Init",{Init:b.Hd.prototype.Init});b.Hd.prototype.Xpa=function(a){this.ke=a};b.Hd.prototype.getPage=function(){return this.Mc};b.b.g("FilmStripPagingModel.prototype.getPage",{getPage:b.Hd.prototype.getPage});b.Hd.prototype.setPage=
function(a,b){a=parseInt(a,10);try{var c=this.getPageCount(),e=this.Mc,f=this.La,h=f;b&&b.pageSize&&(h=b.pageSize);var k=Math.ceil(this.ke/h);if(0>a||a>k-1)throw Error("JET FilmStrip: Invalid 'page' set: "+a);var l=!1;if(a!=e||h!=f){if(!1===this.handleEvent("beforePage",{page:a,previousPage:e}))return Promise.reject();l=!0}this.Mc=a;this.La=h;var m=this.getPageCount(),n=this;return new Promise(function(b){c!=m&&n.handleEvent("pageCount",{pageCount:m,previousPageCount:c});l&&n.handleEvent("page",{page:a,
previousPage:e});b(null)})}catch(p){return Promise.reject(p)}};b.b.g("FilmStripPagingModel.prototype.setPage",{setPage:b.Hd.prototype.setPage});b.Hd.prototype.getStartItemIndex=function(){return this.Mc*this.La};b.b.g("FilmStripPagingModel.prototype.getStartItemIndex",{getStartItemIndex:b.Hd.prototype.getStartItemIndex});b.Hd.prototype.getEndItemIndex=function(){return Math.min(this.getStartItemIndex()+this.La,this.ke)-1};b.b.g("FilmStripPagingModel.prototype.getEndItemIndex",{getEndItemIndex:b.Hd.prototype.getEndItemIndex});
b.Hd.prototype.getPageCount=function(){return Math.ceil(this.ke/this.La)};b.b.g("FilmStripPagingModel.prototype.getPageCount",{getPageCount:b.Hd.prototype.getPageCount});b.Hd.prototype.totalSize=function(){return this.ke};b.b.g("FilmStripPagingModel.prototype.totalSize",{totalSize:b.Hd.prototype.totalSize});b.Hd.prototype.totalSizeConfidence=function(){return"actual"};b.b.g("FilmStripPagingModel.prototype.totalSizeConfidence",{totalSizeConfidence:b.Hd.prototype.totalSizeConfidence});(function(){function a(a){var b=
f("\x3cdiv\x3e\x3c/div\x3e");b.text(a);return b[0].innerHTML}function d(a){a.css("-webkit-transform",p).css("-ms-transform",p).css("transform",p)}function c(a,b){a.css("-webkit-transform",b).css("-ms-transform",b).css("transform",b)}b.ya("oj.ojFilmStrip",f.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{maxItemsPerPage:0,orientation:"horizontal",currentItem:0,arrowPlacement:"adjacent",arrowVisibility:"auto"},_ComponentCreate:function(){this._super();var a=this.element;
a.addClass("oj-filmstrip oj-component").attr("tabindex",0).attr("role","region");a.uniqueId();a=this.options;a.disabled&&b.r.warn(da);if(a.orientation!==w&&a.orientation!==fa)throw Error(s+a.orientation);if(a.arrowPlacement!==e&&a.arrowPlacement!==Y)throw Error(q+a.arrowPlacement);if(a.arrowVisibility!==ba&&a.arrowVisibility!==x&&a.arrowVisibility!==y&&a.arrowVisibility!==h)throw Error(t+a.arrowVisibility);this.lz=this.eventNamespace+"Touch";this.zE=this.eventNamespace+"Mouse";this.X3=this.eventNamespace+
"Key";this.EO=this.eventNamespace+"NavArrowHoverable";this.Aa(!0)},refresh:function(){this._super();this.Aa(!1)},getItemsPerPage:function(){return this.zq},getPagingModel:function(){return this.ge},tl:function(){this._super();this.Xc&&this.Aa(this.Xc[0])},pn:function(){this._super();this.Xc&&this.Aa(this.Xc[0])},Aa:function(a){if(this.cw()){this.Xc=null;this.wf="rtl"===this.bc();this.An=b.v.Rd();var c=this.element,d=this;a?(this.zq=0,this.UJ=function(a){d.TJ(a)},this.ge=new b.Hd,this.Fn=0,this.cx=
-1,this.vk=function(){d.tq()},this.ah=function(){d.Ve()},this.An&&(this.zX=function(a){d.bK(a)},this.yX=function(a){d.aK(a)},this.$J=function(a){d.ZJ(a)},this.j$()),this.oX=function(a){d.Cfa(a)},this.pX=function(a){d.Dfa(a)},this.rX=function(a){d.Ffa(a)},this.f$(),this.nX=function(a){d.rq(a)},this.d$()):this.OU();for(var e=c.children(),f=0;f<e.length;f++)b.Components.Hg(e[f]);a&&(a=this.ge,a.Xpa(e.length),a.on("page",this.UJ));this.yma();this.YS();for(f=0;f<e.length;f++)b.Components.Qf(e[f]);b.v.Nh(c[0],
this.ah)}else c=!1,this.Xc&&(c=this.Xc[0]),this.Xc=[a||c]},_destroy:function(){this.An&&(this.Uja(),this.$J=this.yX=this.zX=null);this.Nja();this.rX=this.pX=this.oX=null;this.Lja();this.nX=null;this.OU();this.ge.off("page",this.UJ);this.vk=this.ah=this.ge=this.UJ=null;var a=this.element;a.removeClass("oj-filmstrip oj-component "+J).removeAttr("tabindex role");a.removeUniqueId();this._super()},OU:function(){b.v.Oi(this.element[0],this.ah);this.cx=-1;this.Cx&&(clearTimeout(this.Cx),this.Cx=null);for(var a=
this.JB(),c=0;c<a.length;c++)b.Components.Hg(a[c]);this.LT();this.bJ().unwrap();this.gma();for(c=0;c<a.length;c++)b.Components.Qf(a[c])},_setOption:function(a,c,d){var f=this.options,g=!1,k=-1,l=this.ge,m=l.getPage();switch(a){case "disabled":b.r.warn(da);break;case "orientation":if(c!==w&&c!==fa)throw Error(s+c);g=f.orientation!=c;break;case "maxItemsPerPage":g=f.maxItemsPerPage!=c;break;case "arrowPlacement":if(c!==e&&c!==Y)throw Error(q+c);g=f.arrowPlacement!=c;break;case "arrowVisibility":if(c!==
ba&&c!==x&&c!==y&&c!==h)throw Error(t+c);g=f.arrowVisibility!=c;break;case B:if(f.currentItem!=c&&(k=this.DI(c),0>k||k>=l.getPageCount()))throw Error(r+c);}this._super(a,c,d);switch(a){case B:-1<k&&k!=m&&l.setPage(k)}g&&this.Aa(!1)},Ve:function(){if(!this.kT)this.kT=!0,this.YS(!0),this.kT=!1;else if(!this.Cx){var a=this;this.Cx=setTimeout(function(){a.Cx=null;a.Ve()},0)}},Kb:function(){return this.options.orientation!==fa},Cw:function(){return this.Kb()?this.wf?"right":"left":"top"},dq:function(){return this.Kb()?
"width":"height"},cw:function(){var a=document.createElement("div"),b=a.style;b.position="absolute";b.width="10px";b.height="10px";b=this.element[0];b.appendChild(a);var c=!1;try{c=0<a.offsetWidth&&0<a.offsetHeight}catch(d){}b.removeChild(a);return c},yma:function(){var a=this.element,b=this.Kb();a.children().addClass(C).wrap("\x3cdiv class\x3d'"+E+" "+O+"'\x3e\x3c/div\x3e");var c=this.Cw();this.vj=c=a.children().wrapAll("\x3cdiv class\x3d'"+E+" "+H+"' style\x3d'"+c+": 0px;'\x3e\x3c/div\x3e").parent();
var d=this.options;d.arrowVisibility!==x&&d.arrowPlacement===e&&(this.PH=c.wrap("\x3cdiv class\x3d'"+E+" oj-filmstrip-content-container'\x3e\x3c/div\x3e").parent());a.addClass(E);b||a.addClass(R);d.arrowVisibility!==x&&(this.Ck=this.uba(),this.uj=this.gba(),this.IK()&&this.kla())},gma:function(){var a=this.element,b=this.JB();this.Jla();this.Ck&&(this.Kp(this.Ck),this.Ck=null);this.uj&&(this.Kp(this.uj),this.uj=null);var c=a.children(T+A);c&&c.remove();b.removeClass(C).unwrap().unwrap();this.vj=null;
this.PH&&(b.unwrap(),this.PH=null);a.removeClass(E+" "+R)},kla:function(){this.element.on("mouseenter"+this.EO,function(a){f(a.currentTarget).hasClass("oj-disabled")||f(a.currentTarget).addClass(J)}).on("mouseleave"+this.EO,function(a){f(a.currentTarget).removeClass(J)})},Jla:function(){this.element.off(this.EO)},IK:function(){var a=this.options,b=a.arrowVisibility;return b===y||b===h&&a.arrowPlacement===Y},Zfa:function(){return 0<this.ge.getPage()},Yfa:function(){var a=this.ge;return a.getPage()<
a.getPageCount()-1},Jia:function(){if(this.Zfa()){var a=this.ge;a.setPage(a.getPage()-1)}},hia:function(){if(this.Yfa()){var a=this.ge;a.setPage(a.getPage()+1)}},WU:function(a,b){this.options.arrowPlacement===e?b.css("visibility",a?"":x):b.parent().css("display",a?"":M)},qma:function(){if(this.options.arrowVisibility!==x){var a=this.ge,b=a.getPage(),a=a.getPageCount();this.WU(0!==b,this.Ck);this.WU(b!==a-1,this.uj)}},uba:function(){var b=this.element,c=this.Kb()?V:ga,d=this.mU(c);this.options.arrowPlacement===
Y?b.append(d):b.prepend(d);var b=a(this.A("labelAccArrowPreviousPage")),e=a(this.A("tipArrowPreviousPage")),c=this.lU(d,c,b,e),f=this;c.on("click",function(){f.Jia()});return c},gba:function(){var b=this.element,c=this.Kb()?G:I,d=this.mU(c);b.append(d);var b=a(this.A("labelAccArrowNextPage")),e=a(this.A("tipArrowNextPage")),c=this.lU(d,c,b,e),f=this;c.on("click",function(){f.hia()});return c},mU:function(a){var b=f(document.createElement("div"));b.addClass(A+" "+a);this.options.arrowPlacement===Y&&
(b.addClass("oj-filmstrip-arrow-container-overlay"),this.IK()&&b.addClass(z));return b},lU:function(a,b,c,d){var f="\x3cdiv class\x3d'"+D+" oj-default oj-enabled "+b+"' role\x3d'button' tabindex\x3d'-1'";a.append(f+("\x3e\x3cspan class\x3d'oj-filmstrip-arrow-icon "+b+" oj-component-icon'\x3e\x3c/span\x3e\x3c/div\x3e"));b=this.element.attr("id");a=a.children(T+D).eq(0);a.uniqueId();f=a.attr("id");c&&a.attr("aria-label",c);d&&a.attr("title",d);a.attr("aria-labelledby",f+" "+b);this._hoverable(a);this.Op(a);
this.options.arrowPlacement===e&&this.IK()&&a.addClass(z);return a},bJ:function(){return this.vj.find(T+O)},JB:function(){return this.vj.find(T+C)},Qn:function(){return this.vj.children(T+Q)},LT:function(){var a=this.vj;this.Qn().css(v,p).css(ca,p);this.bJ().css(v,p).css(ca,p);a.css(this.dq(),p)},YS:function(a){this.LT();var c=this.options,d=this.Kb(),h=c.maxItemsPerPage,q=1>h,l=this.element,t=this.bJ();if(0>this.cx){var m=this.kW(c.currentItem),m=f(t[m]),n=m.children(T+C);n.css(k,p);b.Components.Nm(n[0]);
this.cx=d?m.width():m.height()}m=d?l.width():l.height();c.arrowVisibility!==x&&c.arrowPlacement===e&&(l=l.children(T+A).eq(0),d=d?l.width():l.height(),m-=2*d);this.Fn=m;q||(d=Math.max(Math.floor(m/this.cx),1),d<h&&(h=d));h=q?Math.max(Math.floor(m/this.cx),1):h;q=m/h;t.css(v,q+aa).css(ca,q+aa);q=Math.ceil(t.length/h);n=this.Qn();d=!1;l=this.ge;if(l.getPageCount()!=q||this.zq!=h||!n||1>n.length){d=!0;if(a)for(var u=0;u<t.length;u++)b.Components.Hg(t[u]);n&&0<n.length&&t.unwrap();for(u=0;u<t.length;u+=
h)t.slice(u,u+h).wrapAll("\x3cdiv class\x3d'"+E+" "+Q+"' style\x3d'"+k+": "+M+";' "+g+"\x3d'true'\x3e\x3c/div\x3e");if(a)for(u=0;u<t.length;u++)b.Components.Qf(t[u])}n=this.Qn();n.css(v,m+aa).css(ca,m+aa);a=this.PH;this.vj.css(this.dq(),m);a&&a.css(this.dq(),m);a=0;if(c.currentItem||0===c.currentItem)a=this.DI(c.currentItem,h);l.getPageCount()!=q||this.zq!=h||l.getPage()!=a?l.setPage(a,{pageSize:h}):d&&(c=l.getPage(),this.TJ({previousPage:c,page:c}))},TJ:function(a){var b=a.page,c=a.previousPage;
a=this.vj;var d=this.Qn(),e=this.ge.La,g=0>c||c==b||this.zq!=e;this.zq=e;e=null;g||(e=f(d[c]));var h=this.Cw(),k=f(d[b]),q=k.is(u);q&&this.BM(k);var l=this.Ks;-1<c&&!g&&(l=!0,a.css(this.dq(),2*this.Fn),b<c&&q&&a.css(h,-this.Fn+aa),b>c?(e.addClass(N),k.addClass(F)):(e.addClass(X),k.addClass(P)));if(l){var t=this,m=this.Ks;m&&0>c&&d.filter(S).addClass(L);setTimeout(function(){t.xV(b,c,g,m)},25)}else this.xV(b,c,g)},xV:function(a,b,e,g){var h=this.vj;e||(this.lT=!0,h.on("transitionend"+this.eventNamespace+
" webkitTransitionEnd"+this.eventNamespace,this.vk));e?this.tq():(e=this.Qn(),g&&d(e),-1<b?(g=a>b,b=f(e[b]),a=f(e[a]),b.addClass(L),a.addClass(L),g?(b.removeClass(N),a.removeClass(F),b.addClass(U),a.addClass(K)):(b.removeClass(X),a.removeClass(P),b.addClass(W),a.addClass(Z))):g&&(a=e.filter(S),c(a,"translate3d(0, 0, 0)")))},tq:function(){this.lT=!1;var a=this.vj,c=this.Cw();a.off(this.eventNamespace).css(this.dq(),this.Fn).css(c,"0px");c=null;if(b.rd.QD(a[0])||this.uj&&b.rd.QD(this.uj[0])||this.Ck&&
b.rd.QD(this.Ck[0]))c=document.activeElement;for(var a=this.ge.getPage(),e=this.Qn(),g=0;g<e.length;g++)g!=a&&this.FX(f(e[g]));e.removeClass(L+" "+U+" "+K+" "+W+" "+Z);d(e);this.qma();c&&f(c).is(u)&&(c=this.element,(e=b.rd.S2(e[a]))?b.rd.wy(e):b.rd.wy(c[0]));this.DI(this.options.currentItem)!=a&&(a=this.aW(a),this.option(B,a,{_context:{Hc:!0}}))},kW:function(a){var c=-1,d=this.JB();if("number"===typeof a)0<=a&&a<d.length&&(c=a);else if("string"===typeof a&&b.v.rE(a))for(var e=0;e<d.length;e++){var f=
d[e].id;if(f&&0<f.length&&f===a){c=e;break}}return c},DI:function(a,b){var c=this.kW(a),d=-1;-1<c&&(void 0===b&&(b=this.zq),d=Math.floor(c/b));return d},aW:function(a,b,c){var d=this.ge;void 0===b&&(b=d.getPageCount());return 0<=a&&a<b&&(b=this.JB(),void 0===c&&(c=this.zq),a*=c,a<b.length)?(c=b[a].id)&&0<c.length?c:a:-1},FX:function(a){b.Components.dp(a[0]);a.css(k,M).attr(g,"true");a.find(T+C).css(k,M)},BM:function(a){a.css(k,p).removeAttr(g);a.find(T+C).css(k,p);b.Components.Nm(a[0])},d$:function(){this.element.on("keydown"+
this.X3,this.nX)},Lja:function(){this.element.off(this.X3)},f$:function(){this.element.on("mousedown"+this.zE,this.oX).on("mousemove"+this.zE,this.pX).on("mouseup"+this.zE,this.rX)},Nja:function(){this.element.off(this.zE)},j$:function(){this.element.on("touchstart"+this.lz,this.zX).on("touchmove"+this.lz,this.yX).on("touchend"+this.lz,this.$J).on("touchcancel"+this.lz,this.$J)},Uja:function(){this.element.off(this.lz)},rq:function(a){var b=this.ge,c=b.getPage(),d=-1;switch(a.keyCode){case f.ui.keyCode.RIGHT:d=
this.wf?c-1:c+1;break;case f.ui.keyCode.LEFT:d=this.wf?c+1:c-1;break;case f.ui.keyCode.DOWN:d=c+1;break;case f.ui.keyCode.UP:d=c-1;break;case f.ui.keyCode.HOME:d=0;break;case f.ui.keyCode.END:d=b.getPageCount()-1;break;default:return}-1<d&&d<b.getPageCount()&&b.setPage(d);a.preventDefault()},Cfa:function(a){this.hV(a.originalEvent)},Dfa:function(a){this.gV(a,a.originalEvent)},Ffa:function(){this.fV()},bK:function(a){a=a.originalEvent.touches;1===a.length&&this.hV(a[0])},aK:function(a){this.gV(a,a.originalEvent.touches[0]);
(this.pi||this.Lq)&&a.preventDefault()},ZJ:function(){this.fV()},hV:function(a){if(1<this.ge.getPageCount()&&!this.lT){this.pi=!0;this.Ks=!1;var b=this.Kb();this.qD=b?a.pageX:a.pageY;this.d1=b?a.pageY:a.pageX}},qga:function(a){var b=this.Kb();this.qD=b?a.pageX:a.pageY;this.d1=b?a.pageY:a.pageX;a=this.Cw();var b=this.vj,c=this.ge,d=this.Qn(),e=1;0<c.getPage()&&(this.BM(f(d[c.getPage()-1])),b.css(a,-this.Fn+aa),e++);c.getPage()<c.getPageCount()-1&&(this.BM(f(d[c.getPage()+1])),e++);1<e&&b.css(this.dq(),
e*this.Fn);this.mM=parseInt(b.css(a),10)},gV:function(a,b){if(this.pi){var d=this.Kb(),e=(d?b.pageX:b.pageY)-this.qD;Math.abs((d?b.pageY:b.pageX)-this.d1)>Math.abs(e)&&(this.Lq=this.pi=!1);if(this.Ks){var g=d&&this.wf?0<e:0>e,h=this.ge,k=h.getPage();if(g&&k<h.getPageCount()-1||!g&&0<k){var q=this.element[0],t=Math.min(m*(d?q.offsetWidth:q.offsetHeight),n),v=this.Cw(),p=this.vj,q=this.Qn();Math.abs(e)>=t?(d=g?k+1:k-1,this.aW(d),k=g?k-1:k+1,-1<k&&k<h.getPageCount()&&this.FX(f(q[k])),g&&-1<k&&(q=parseInt(p.css(v),
10),p.css(v,q+this.Fn+aa)),p.css(this.dq(),2*this.Fn),this.pi=!1,h.setPage(d)):(h=d&&this.wf?-e:e,h=d?"translate3d("+h+"px, 0, 0)":"translate3d(0, "+h+"px, 0)",c(q.filter(S),h));this.Lq=!0}this.Lq&&(a.preventDefault(),a.stopPropagation())}else Math.abs(e)>l&&(this.qga(b),this.Ks=!0)}},fV:function(){if(this.pi&&this.Ks){var a=this.ge.getPage();this.TJ({previousPage:a,page:a})}this.Lq=this.Ks=this.pi=!1},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-filmstrip-start-arrow"===
a?this.widget().find(T+D+T+V)[0]:"oj-filmstrip-end-arrow"===a?this.widget().find(T+D+T+G)[0]:"oj-filmstrip-top-arrow"===a?this.widget().find(T+D+T+ga)[0]:"oj-filmstrip-bottom-arrow"===a?this.widget().find(T+D+T+I)[0]:null},getSubIdByNode:function(a){for(var b=this.getNodeBySubId({subId:"oj-filmstrip-start-arrow"}),c=this.getNodeBySubId({subId:"oj-filmstrip-end-arrow"}),d=this.getNodeBySubId({subId:"oj-filmstrip-top-arrow"}),e=this.getNodeBySubId({subId:"oj-filmstrip-bottom-arrow"}),f=this.element[0];a&&
a!=f;){if(a===b)return{subId:"oj-filmstrip-start-arrow"};if(a===c)return{subId:"oj-filmstrip-end-arrow"};if(a===d)return{subId:"oj-filmstrip-top-arrow"};if(a===e)return{subId:"oj-filmstrip-bottom-arrow"};a=a.parentElement}return null}});var e="adjacent",g="aria-hidden",h="auto",k="display",l=3,m=.33,n=100,p="",r="JET FilmStrip: Value of 'currentItem' option not found: ",s="JET FilmStrip: Unsupported value set as 'orientation' option: ",q="Unsupported value set as 'arrowPlacement' option: ",t="Unsupported value set as 'arrowVisibility' option: ",
v="flex-basis",x="hidden",u=":hidden",w="horizontal",y="hover",B="currentItem",M="none",I="oj-bottom",G="oj-end",D="oj-filmstrip-arrow",A="oj-filmstrip-arrow-container",z="oj-filmstrip-arrow-transition",E="oj-filmstrip-container",J="oj-filmstrip-hover",C="oj-filmstrip-item",O="oj-filmstrip-item-container",Q="oj-filmstrip-page",H="oj-filmstrip-pages-container",L="oj-filmstrip-transition",F="oj-filmstrip-transition-next-newpage-from",N="oj-filmstrip-transition-next-oldpage-from",P="oj-filmstrip-transition-prev-newpage-from",
X="oj-filmstrip-transition-prev-oldpage-from",K="oj-filmstrip-transition-next-newpage-to",U="oj-filmstrip-transition-next-oldpage-to",Z="oj-filmstrip-transition-prev-newpage-to",W="oj-filmstrip-transition-prev-oldpage-to",R="oj-filmstrip-vertical",V="oj-start",ga="oj-top",Y="overlay",T=".",aa="px",fa="vertical",ba="visible",S=":visible",ca="-webkit-flex-basis",da="JET FilmStrip: 'disabled' option not supported"})()});