//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:30:16 PM PST 
//


package com.oracle.demo.ops.domain;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Address complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="Address">
 *   &lt;complexContent>
 *     &lt;extension base="{http://demo.oracle.com/ops/domain/schema/common}BaseEntity">
 *       &lt;sequence>
 *         &lt;element name="Addressee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLine2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address", namespace = "http://demo.oracle.com/ops/domain/schema/common", propOrder = {
    "addressee",
    "addressLine1",
    "addressLine2",
    "city",
    "state",
    "postalCode"
})
public class Address
    extends BaseEntity
    implements Serializable
{

  private final static long serialVersionUID = 678L;
  @XmlElement(name = "Addressee")
  protected String addressee;
  @XmlElement(name = "AddressLine1")
  protected String addressLine1;
  @XmlElement(name = "AddressLine2")
  protected String addressLine2;
  @XmlElement(name = "City")
  protected String city;
  @XmlElement(name = "State")
  protected String state;
  @XmlElement(name = "PostalCode")
  protected String postalCode;

  /**
   * Gets the value of the addressee property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getAddressee()
  {
    return addressee;
  }

  /**
   * Sets the value of the addressee property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAddressee(String value)
  {
    this.addressee = value;
  }

  /**
   * Gets the value of the addressLine1 property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getAddressLine1()
  {
    return addressLine1;
  }

  /**
   * Sets the value of the addressLine1 property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAddressLine1(String value)
  {
    this.addressLine1 = value;
  }

  /**
   * Gets the value of the addressLine2 property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getAddressLine2()
  {
    return addressLine2;
  }

  /**
   * Sets the value of the addressLine2 property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAddressLine2(String value)
  {
    this.addressLine2 = value;
  }

  /**
   * Gets the value of the city property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getCity()
  {
    return city;
  }

  /**
   * Sets the value of the city property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setCity(String value)
  {
    this.city = value;
  }

  /**
   * Gets the value of the state property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getState()
  {
    return state;
  }

  /**
   * Sets the value of the state property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setState(String value)
  {
    this.state = value;
  }

  /**
   * Gets the value of the postalCode property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getPostalCode()
  {
    return postalCode;
  }

  /**
   * Sets the value of the postalCode property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setPostalCode(String value)
  {
    this.postalCode = value;
  }

}
