//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:30:16 PM PST 
//


package com.oracle.demo.ops.domain;

import java.io.Serializable;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for BaseEntity complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="BaseEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{http://demo.oracle.com/ops/domain/schema/common}BaseObject">
 *       &lt;sequence>
 *         &lt;element name="CreatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ModifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseEntity", namespace = "http://demo.oracle.com/ops/domain/schema/common", propOrder = {
    "createdDate",
    "modifiedDate"
})
@XmlSeeAlso({
                Address.class,
                ShippingService.class,
                BaseParameter.class,
                Shipment.class,
                Parcel.class,
                ParcelEvent.class
            })
public abstract class BaseEntity
    extends BaseObject
    implements Serializable
{

  private final static long serialVersionUID = 678L;
  @XmlElement(name = "CreatedDate", type = String.class)
  @XmlJavaTypeAdapter(Adapter1.class)
  @XmlSchemaType(name = "dateTime")
  protected Calendar createdDate;
  @XmlElement(name = "ModifiedDate", type = String.class)
  @XmlJavaTypeAdapter(Adapter1.class)
  @XmlSchemaType(name = "dateTime")
  protected Calendar modifiedDate;

  /**
   * Gets the value of the createdDate property.
   *
   * @return possible object is
   *         {@link String }
   */
  public Calendar getCreatedDate()
  {
    return createdDate;
  }

  /**
   * Sets the value of the createdDate property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setCreatedDate(Calendar value)
  {
    this.createdDate = value;
  }

  /**
   * Gets the value of the modifiedDate property.
   *
   * @return possible object is
   *         {@link String }
   */
  public Calendar getModifiedDate()
  {
    return modifiedDate;
  }

  /**
   * Sets the value of the modifiedDate property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setModifiedDate(Calendar value)
  {
    this.modifiedDate = value;
  }

}
