//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:30:16 PM PST 
//


package com.oracle.demo.ops.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.oracle.demo.ops.domain package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory
{


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle.demo.ops.domain
   */
  public ObjectFactory()
  {
  }

  /**
   * Create an instance of {@link GetShipmentByIdResponse }
   */
  public GetShipmentByIdResponse createGetShipmentByIdResponse()
  {
    return new GetShipmentByIdResponse();
  }

  /**
   * Create an instance of {@link WebServiceResponseHeader }
   */
  public WebServiceResponseHeader createWebServiceResponseHeader()
  {
    return new WebServiceResponseHeader();
  }

  /**
   * Create an instance of {@link Shipment }
   */
  public Shipment createShipment()
  {
    return new Shipment();
  }

  /**
   * Create an instance of {@link SendNewShipmentViaJMSResponse }
   */
  public SendNewShipmentViaJMSResponse createSendNewShipmentViaJMSResponse()
  {
    return new SendNewShipmentViaJMSResponse();
  }

  /**
   * Create an instance of {@link CreateShipmentResponse }
   */
  public CreateShipmentResponse createCreateShipmentResponse()
  {
    return new CreateShipmentResponse();
  }

  /**
   * Create an instance of {@link GetShipmentByExternalIdResponse }
   */
  public GetShipmentByExternalIdResponse createGetShipmentByExternalIdResponse()
  {
    return new GetShipmentByExternalIdResponse();
  }

  /**
   * Create an instance of {@link SendNewShipmentViaJMSRequest }
   */
  public SendNewShipmentViaJMSRequest createSendNewShipmentViaJMSRequest()
  {
    return new SendNewShipmentViaJMSRequest();
  }

  /**
   * Create an instance of {@link WebServiceRequestHeader }
   */
  public WebServiceRequestHeader createWebServiceRequestHeader()
  {
    return new WebServiceRequestHeader();
  }

  /**
   * Create an instance of {@link CreateShipmentRequest }
   */
  public CreateShipmentRequest createCreateShipmentRequest()
  {
    return new CreateShipmentRequest();
  }

  /**
   * Create an instance of {@link GetShipmentByIdRequest }
   */
  public GetShipmentByIdRequest createGetShipmentByIdRequest()
  {
    return new GetShipmentByIdRequest();
  }

  /**
   * Create an instance of {@link GetShipmentByExternalIdRequest }
   */
  public GetShipmentByExternalIdRequest createGetShipmentByExternalIdRequest()
  {
    return new GetShipmentByExternalIdRequest();
  }

  /**
   * Create an instance of {@link ParcelEvent }
   */
  public ParcelEvent createParcelEvent()
  {
    return new ParcelEvent();
  }

  /**
   * Create an instance of {@link Parcel }
   */
  public Parcel createParcel()
  {
    return new Parcel();
  }

  /**
   * Create an instance of {@link Address }
   */
  public Address createAddress()
  {
    return new Address();
  }

  /**
   * Create an instance of {@link ShippingService }
   */
  public ShippingService createShippingService()
  {
    return new ShippingService();
  }

  /**
   * Create an instance of {@link GetParcelEventLogResponse }
   */
  public GetParcelEventLogResponse createGetParcelEventLogResponse()
  {
    return new GetParcelEventLogResponse();
  }

  /**
   * Create an instance of {@link AddParcelLogEventJMSPROXYResponse }
   */
  public AddParcelLogEventJMSPROXYResponse createAddParcelLogEventJMSPROXYResponse()
  {
    return new AddParcelLogEventJMSPROXYResponse();
  }

  /**
   * Create an instance of {@link AddParcelLogEventJMSPROXYRequest }
   */
  public AddParcelLogEventJMSPROXYRequest createAddParcelLogEventJMSPROXYRequest()
  {
    return new AddParcelLogEventJMSPROXYRequest();
  }

  /**
   * Create an instance of {@link GetParcelEventLogRequest }
   */
  public GetParcelEventLogRequest createGetParcelEventLogRequest()
  {
    return new GetParcelEventLogRequest();
  }

  /**
   * Create an instance of {@link GetParcelByIdResponse }
   */
  public GetParcelByIdResponse createGetParcelByIdResponse()
  {
    return new GetParcelByIdResponse();
  }

  /**
   * Create an instance of {@link GetParcelByIdRequest }
   */
  public GetParcelByIdRequest createGetParcelByIdRequest()
  {
    return new GetParcelByIdRequest();
  }

}
