//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:30:16 PM PST 
//


package com.oracle.demo.ops.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParcelStatus.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="ParcelStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BILLING_INFO_RECEIVED"/>
 *     &lt;enumeration value="PARCEL_RECEIVED"/>
 *     &lt;enumeration value="IN_TRANSIT"/>
 *     &lt;enumeration value="DELIVERED"/>
 *     &lt;enumeration value="DELIVERY_EXCEPTION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "ParcelStatus", namespace = "http://demo.oracle.com/ops/domain/schema/shipping")
@XmlEnum
public enum ParcelStatus
{

  BILLING_INFO_RECEIVED,
  PARCEL_RECEIVED,
  IN_TRANSIT,
  DELIVERED,
  DELIVERY_EXCEPTION;

  public String value()
  {
    return name();
  }

  public static ParcelStatus fromValue(String v)
  {
    return valueOf(v);
  }

}
