//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:30:16 PM PST 
//


package com.oracle.demo.ops.domain;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParcelType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ParcelType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://demo.oracle.com/ops/domain/schema/common}BaseEntity">
 *       &lt;sequence>
 *         &lt;element name="ShipmentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Contents" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Width" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Length" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ParcelStatus" type="{http://demo.oracle.com/ops/domain/schema/shipping}ParcelStatus"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParcelType", namespace = "http://demo.oracle.com/ops/domain/schema/shipping", propOrder = {
    "shipmentId",
    "contents",
    "height",
    "width",
    "length",
    "weight",
    "parcelStatus"
})
@XmlRootElement(name = "Parcel", namespace = "http://demo.oracle.com/ops/domain/schema/shipping")
public class Parcel
    extends BaseEntity
    implements Serializable
{

  private final static long serialVersionUID = 678L;
  @XmlElement(name = "ShipmentId")
  protected int shipmentId;
  @XmlElement(name = "Contents", required = true)
  protected String contents;
  @XmlElement(name = "Height")
  protected int height;
  @XmlElement(name = "Width")
  protected int width;
  @XmlElement(name = "Length")
  protected int length;
  @XmlElement(name = "Weight")
  protected int weight;
  @XmlElement(name = "ParcelStatus", required = true)
  protected ParcelStatus parcelStatus;

  /**
   * Gets the value of the shipmentId property.
   */
  public int getShipmentId()
  {
    return shipmentId;
  }

  /**
   * Sets the value of the shipmentId property.
   */
  public void setShipmentId(int value)
  {
    this.shipmentId = value;
  }

  /**
   * Gets the value of the contents property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getContents()
  {
    return contents;
  }

  /**
   * Sets the value of the contents property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setContents(String value)
  {
    this.contents = value;
  }

  /**
   * Gets the value of the height property.
   */
  public int getHeight()
  {
    return height;
  }

  /**
   * Sets the value of the height property.
   */
  public void setHeight(int value)
  {
    this.height = value;
  }

  /**
   * Gets the value of the width property.
   */
  public int getWidth()
  {
    return width;
  }

  /**
   * Sets the value of the width property.
   */
  public void setWidth(int value)
  {
    this.width = value;
  }

  /**
   * Gets the value of the length property.
   */
  public int getLength()
  {
    return length;
  }

  /**
   * Sets the value of the length property.
   */
  public void setLength(int value)
  {
    this.length = value;
  }

  /**
   * Gets the value of the weight property.
   */
  public int getWeight()
  {
    return weight;
  }

  /**
   * Sets the value of the weight property.
   */
  public void setWeight(int value)
  {
    this.weight = value;
  }

  /**
   * Gets the value of the parcelStatus property.
   *
   * @return possible object is
   *         {@link ParcelStatus }
   */
  public ParcelStatus getParcelStatus()
  {
    return parcelStatus;
  }

  /**
   * Sets the value of the parcelStatus property.
   *
   * @param value allowed object is
   *              {@link ParcelStatus }
   */
  public void setParcelStatus(ParcelStatus value)
  {
    this.parcelStatus = value;
  }

}
