//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:30:16 PM PST 
//


package com.oracle.demo.ops.domain;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShippingService complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ShippingService">
 *   &lt;complexContent>
 *     &lt;extension base="{http://demo.oracle.com/ops/domain/schema/common}BaseEntity">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Cost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShippingService", namespace = "http://demo.oracle.com/ops/domain/schema/shipping", propOrder = {
    "name",
    "description",
    "cost"
})
public class ShippingService
    extends BaseEntity
    implements Serializable
{

  private final static long serialVersionUID = 678L;
  @XmlElement(name = "Name")
  protected String name;
  @XmlElement(name = "Description")
  protected String description;
  @XmlElement(name = "Cost")
  protected Double cost;

  /**
   * Gets the value of the name property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getName()
  {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setName(String value)
  {
    this.name = value;
  }

  /**
   * Gets the value of the description property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getDescription()
  {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setDescription(String value)
  {
    this.description = value;
  }

  /**
   * Gets the value of the cost property.
   *
   * @return possible object is
   *         {@link Double }
   */
  public Double getCost()
  {
    return cost;
  }

  /**
   * Sets the value of the cost property.
   *
   * @param value allowed object is
   *              {@link Double }
   */
  public void setCost(Double value)
  {
    this.cost = value;
  }

}
