//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:30:16 PM PST 
//


package com.oracle.demo.ops.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShipmentType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ShipmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://demo.oracle.com/ops/domain/schema/common}BaseEntity">
 *       &lt;sequence>
 *         &lt;element name="ExternalReferenceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ToAddress" type="{http://demo.oracle.com/ops/domain/schema/common}Address"/>
 *         &lt;element name="FromAddress" type="{http://demo.oracle.com/ops/domain/schema/common}Address"/>
 *         &lt;element name="ShippingService" type="{http://demo.oracle.com/ops/domain/schema/shipping}ShippingService"/>
 *         &lt;element ref="{http://demo.oracle.com/ops/domain/schema/shipping}Parcel" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentType", namespace = "http://demo.oracle.com/ops/domain/schema/shipping", propOrder = {
    "externalReferenceId",
    "toAddress",
    "fromAddress",
    "shippingService",
    "parcels"
})
@XmlRootElement(name = "Shipment", namespace = "http://demo.oracle.com/ops/domain/schema/shipping")
public class Shipment
    extends BaseEntity
    implements Serializable
{

  private final static long serialVersionUID = 678L;
  @XmlElement(name = "ExternalReferenceId", required = true)
  protected String externalReferenceId;
  @XmlElement(name = "ToAddress", required = true)
  protected Address toAddress;
  @XmlElement(name = "FromAddress", required = true)
  protected Address fromAddress;
  @XmlElement(name = "ShippingService", required = true)
  protected ShippingService shippingService;
  @XmlElement(name = "Parcel", required = true)
  protected List<Parcel> parcels;

  /**
   * Gets the value of the externalReferenceId property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getExternalReferenceId()
  {
    return externalReferenceId;
  }

  /**
   * Sets the value of the externalReferenceId property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setExternalReferenceId(String value)
  {
    this.externalReferenceId = value;
  }

  /**
   * Gets the value of the toAddress property.
   *
   * @return possible object is
   *         {@link Address }
   */
  public Address getToAddress()
  {
    return toAddress;
  }

  /**
   * Sets the value of the toAddress property.
   *
   * @param value allowed object is
   *              {@link Address }
   */
  public void setToAddress(Address value)
  {
    this.toAddress = value;
  }

  /**
   * Gets the value of the fromAddress property.
   *
   * @return possible object is
   *         {@link Address }
   */
  public Address getFromAddress()
  {
    return fromAddress;
  }

  /**
   * Sets the value of the fromAddress property.
   *
   * @param value allowed object is
   *              {@link Address }
   */
  public void setFromAddress(Address value)
  {
    this.fromAddress = value;
  }

  /**
   * Gets the value of the shippingService property.
   *
   * @return possible object is
   *         {@link ShippingService }
   */
  public ShippingService getShippingService()
  {
    return shippingService;
  }

  /**
   * Sets the value of the shippingService property.
   *
   * @param value allowed object is
   *              {@link ShippingService }
   */
  public void setShippingService(ShippingService value)
  {
    this.shippingService = value;
  }

  /**
   * Gets the value of the parcels property.
   * <p/>
   * <p/>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the parcels property.
   * <p/>
   * <p/>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getParcels().add(newItem);
   * </pre>
   * <p/>
   * <p/>
   * <p/>
   * Objects of the following type(s) are allowed in the list
   * {@link Parcel }
   */
  public List<Parcel> getParcels()
  {
    if (parcels == null)
    {
      parcels = new ArrayList<Parcel>();
    }
    return this.parcels;
  }

}
