//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:30:16 PM PST 
//


package com.oracle.demo.ops.domain;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebServiceRequestHeaderType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="WebServiceRequestHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SourceSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SourceSystemUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SourceSystemTxId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebServiceRequestHeaderType", namespace = "http://demo.oracle.com/ops/domain/services/common", propOrder = {
    "sourceSystem",
    "sourceSystemUser",
    "sourceSystemTxId"
})
@XmlRootElement(name = "WebServiceRequestHeader", namespace = "http://demo.oracle.com/ops/domain/services/common")
public class WebServiceRequestHeader
    implements Serializable
{

  private final static long serialVersionUID = 678L;
  @XmlElement(name = "SourceSystem")
  protected String sourceSystem;
  @XmlElement(name = "SourceSystemUser")
  protected String sourceSystemUser;
  @XmlElement(name = "SourceSystemTxId")
  protected String sourceSystemTxId;

  /**
   * Gets the value of the sourceSystem property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getSourceSystem()
  {
    return sourceSystem;
  }

  /**
   * Sets the value of the sourceSystem property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setSourceSystem(String value)
  {
    this.sourceSystem = value;
  }

  /**
   * Gets the value of the sourceSystemUser property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getSourceSystemUser()
  {
    return sourceSystemUser;
  }

  /**
   * Sets the value of the sourceSystemUser property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setSourceSystemUser(String value)
  {
    this.sourceSystemUser = value;
  }

  /**
   * Gets the value of the sourceSystemTxId property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getSourceSystemTxId()
  {
    return sourceSystemTxId;
  }

  /**
   * Sets the value of the sourceSystemTxId property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setSourceSystemTxId(String value)
  {
    this.sourceSystemTxId = value;
  }

}
