connect('weblogic','welcome1','t3://localhost:7001')
edit()

startEdit()
cd('/')
cmo.createVirtualTarget('VT-daytrader ')
cd('/VirtualTargets/VT-daytrader')
cmo.setUriPrefix('/dp3')
set('Targets',jarray.array([ObjectName('com.bea:Name=app-cluster,Type=Cluster')], ObjectName))
activate()

startEdit()
cd('/')
cmo.createPartition('dp3')
cd('/Partitions/dp3/SystemFileSystem/dp3')
cmo.setRoot('/u01/wins/wls1221/user_projects/domains/base_domain/partitions/dp3/system')
cmo.setCreateOnDemand(true)
cmo.setPreserved(true)
cd('/Partitions/dp3')
set('AvailableTargets',jarray.array([ObjectName('com.bea:Name=VT-daytrader,Type=VirtualTarget')], ObjectName))
set('DefaultTargets',jarray.array([ObjectName('com.bea:Name=VT-daytrader,Type=VirtualTarget')], ObjectName))
activate()

startEdit()
cmo.createResourceGroup('app3RG')
cd('/Partitions/dp3/ResourceGroups/app3RG')
cmo.setUseDefaultTarget(false)
set('Targets',jarray.array([ObjectName('com.bea:Name=VT-daytrader,Type=VirtualTarget')], ObjectName))
activate()

startEdit()
cd('/Partitions/dp3/ResourceGroups/app3RG')
cmo.createJDBCSystemResource('jdbc/datasources/TradeDataSource')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/TradeDataSource/JDBCResource/jdbc/datasources/TradeDataSource')
cmo.setName('jdbc/datasources/TradeDataSource')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/TradeDataSource/JDBCResource/jdbc/datasources/TradeDataSource/JDBCDataSourceParams/jdbc/datasources/TradeDataSource')
set('JNDINames',jarray.array([String('jdbc/datasources/TradeDataSource')], String))
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/TradeDataSource/JDBCResource/jdbc/datasources/TradeDataSource')
cmo.setDatasourceType('GENERIC')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/TradeDataSource/JDBCResource/jdbc/datasources/TradeDataSource/JDBCDriverParams/jdbc/datasources/TradeDataSource')
cmo.setUrl('jdbc:oracle:thin:@//localhost:1521/pdborcl')
cmo.setDriverName('oracle.jdbc.OracleDriver')
cmo.setPassword('trade')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/TradeDataSource/JDBCResource/jdbc/datasources/TradeDataSource/JDBCConnectionPoolParams/jdbc/datasources/TradeDataSource')
cmo.setTestTableName('SQL ISVALID\r\n\r\n')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/TradeDataSource/JDBCResource/jdbc/datasources/TradeDataSource/JDBCDriverParams/jdbc/datasources/TradeDataSource/Properties/jdbc/datasources/TradeDataSource')
cmo.createProperty('user')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/TradeDataSource/JDBCResource/jdbc/datasources/TradeDataSource/JDBCDriverParams/jdbc/datasources/TradeDataSource/Properties/jdbc/datasources/TradeDataSource/Properties/user')
cmo.setValue('trade')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/TradeDataSource/JDBCResource/jdbc/datasources/TradeDataSource/JDBCDataSourceParams/jdbc/datasources/TradeDataSource')
cmo.setGlobalTransactionsProtocol('EmulateTwoPhaseCommit')
activate()

startEdit()
cd('/Partitions/dp3/ResourceGroups/app3RG')
cmo.createJDBCSystemResource('jdbc/datasources/NoTxTradeDataSource')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/NoTxTradeDataSource/JDBCResource/jdbc/datasources/NoTxTradeDataSource')
cmo.setName('jdbc/datasources/NoTxTradeDataSource')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/NoTxTradeDataSource/JDBCResource/jdbc/datasources/NoTxTradeDataSource/JDBCDataSourceParams/jdbc/datasources/NoTxTradeDataSource')
set('JNDINames',jarray.array([String('jdbc/datasources/NoTxTradeDataSource')], String))
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/NoTxTradeDataSource/JDBCResource/jdbc/datasources/NoTxTradeDataSource')
cmo.setDatasourceType('GENERIC')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/NoTxTradeDataSource/JDBCResource/jdbc/datasources/NoTxTradeDataSource/JDBCDriverParams/jdbc/datasources/NoTxTradeDataSource')
cmo.setUrl('jdbc:oracle:thin:@//localhost:1521/pdborcl')
cmo.setDriverName('oracle.jdbc.OracleDriver')
cmo.setPassword('trade')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/NoTxTradeDataSource/JDBCResource/jdbc/datasources/NoTxTradeDataSource/JDBCConnectionPoolParams/jdbc/datasources/NoTxTradeDataSource')
cmo.setTestTableName('SQL ISVALID\r\n\r\n')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/NoTxTradeDataSource/JDBCResource/jdbc/datasources/NoTxTradeDataSource/JDBCDriverParams/jdbc/datasources/NoTxTradeDataSource/Properties/jdbc/datasources/NoTxTradeDataSource')
cmo.createProperty('user')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/NoTxTradeDataSource/JDBCResource/jdbc/datasources/NoTxTradeDataSource/JDBCDriverParams/jdbc/datasources/NoTxTradeDataSource/Properties/jdbc/datasources/NoTxTradeDataSource/Properties/user')
cmo.setValue('trade')
cd('/Partitions/dp3/ResourceGroups/app3RG/JDBCSystemResources/jdbc/datasources/NoTxTradeDataSource/JDBCResource/jdbc/datasources/NoTxTradeDataSource/JDBCDataSourceParams/jdbc/datasources/NoTxTradeDataSource')
cmo.setGlobalTransactionsProtocol('EmulateTwoPhaseCommit')
activate()

startEdit()
cd('/Partitions/dp3/ResourceGroups/app3RG')
cmo.createFileStore('MyFileStore')
activate()

startEdit()
cd('/Partitions/dp3/ResourceGroups/app3RG')
cmo.createJMSServer('MyJMSServer')
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSServers/MyJMSServer')
cmo.setPersistentStore(getMBean('/Partitions/dp3/ResourceGroups/app3RG/FileStores/MyFileStore'))
activate()

startEdit()
cd('/Partitions/dp3/ResourceGroups/app3RG')
cmo.createJMSSystemResource('MyJMSModule ')
activate()

startEdit()
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule')
cmo.createSubDeployment('MySubdeployment ')
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/SubDeployments/MySubdeployment')
set('Targets',jarray.array([ObjectName('com.bea:Name=MyJMSServer,Type=JMSServer,Partition=dp3,ResourceGroup=app3RG')], ObjectName))
activate()

startEdit()
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule')
cmo.createConnectionFactory('jms/myQueueConnectionFactory ')
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/ConnectionFactories/jms/myQueueConnectionFactory')
cmo.setJNDIName('jms/myQueueConnectionFactory ')
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/ConnectionFactories/jms/myQueueConnectionFactory/SecurityParams/jms/myQueueConnectionFactory')
cmo.setAttachJMSXUserId(false)
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/ConnectionFactories/jms/myQueueConnectionFactory/ClientParams/jms/myQueueConnectionFactory')
cmo.setClientIdPolicy('Restricted')
cmo.setSubscriptionSharingPolicy('Exclusive')
cmo.setMessagesMaximum(10)
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/ConnectionFactories/jms/myQueueConnectionFactory/TransactionParams/jms/myQueueConnectionFactory')
cmo.setXAConnectionFactoryEnabled(true)
activate()

startEdit()
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule')
cmo.createConnectionFactory('jms/myTopicConnectionFactory')
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/ConnectionFactories/jms/myTopicConnectionFactory')
cmo.setJNDIName('jms/myTopicConnectionFactory')
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/ConnectionFactories/jms/myTopicConnectionFactory/SecurityParams/jms/myTopicConnectionFactory')
cmo.setAttachJMSXUserId(false)
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/ConnectionFactories/jms/myTopicConnectionFactory/ClientParams/jms/myTopicConnectionFactory')
cmo.setClientIdPolicy('Restricted')
cmo.setSubscriptionSharingPolicy('Exclusive')
cmo.setMessagesMaximum(10)
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/ConnectionFactories/jms/myTopicConnectionFactory/TransactionParams/jms/myTopicConnectionFactory')
cmo.setXAConnectionFactoryEnabled(true)
activate()

startEdit()
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule')
cmo.createUniformDistributedQueue('jms/TradeBrokerQueue')
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/UniformDistributedQueues/jms/TradeBrokerQueue')
cmo.setJNDIName('jms/TradeBrokerQueue')
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/SubDeployments/MySubdeployment')
set('Targets',jarray.array([ObjectName('com.bea:Name=MyJMSServer,Type=JMSServer,Partition=dp3,ResourceGroup=app3RG')], ObjectName))
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/UniformDistributedQueues/jms/TradeBrokerQueue')
cmo.setSubDeploymentName('MySubdeployment')
activate()

startEdit()
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule')
cmo.createUniformDistributedTopic('jms/TradeStreamerTopic ')
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/UniformDistributedTopics/jms/TradeStreamerTopic')
cmo.setJNDIName('jms/TradeStreamerTopic ')
cmo.setForwardingPolicy('Partitioned')
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/SubDeployments/MySubdeployment')
set('Targets',jarray.array([ObjectName('com.bea:Name=MyJMSServer,Type=JMSServer,Partition=dp3,ResourceGroup=app3RG')], ObjectName))
cd('/Partitions/dp3/ResourceGroups/app3RG/JMSSystemResources/MyJMSModule/JMSResource/MyJMSModule/UniformDistributedTopics/jms/TradeStreamerTopic')
cmo.setSubDeploymentName('MySubdeployment')
activate()

startEdit()
deploy(appName='web', partition='dp3', resourceGroup='app3RG', path='/u01/content/weblogic-innovation-seminars/WInS_Demos/MT-Workshop/Lab2/web-3.0.0.war')
activate()

startEdit()
cd('/')
partitionBean=cmo.lookupPartition('dp3')
startPartitionWait(partitionBean)
activate()

disconnect()
